const base = import.meta.env.BASE_URL;

export const projects = [
  {
    id: "acharya-guru",
    number: "01",
    title: "Acharya Guru",
    tagline: "A spiritual branding project blending traditional wisdom with modern design aesthetics.",
    tags: ["Branding", "Spiritual", "Identity"],
    color: "#B8860B",
    thumbnail: `${base}acharya guru/thumbnail.jpg`,
    images: [
      { src: `${base}acharya guru/1.jpg`, span: "" },
      { src: `${base}acharya guru/2.jpg`, span: "" },
      { src: `${base}acharya guru/3.jpg`, span: "" },
      { src: `${base}acharya guru/4.jpg`, span: "" },
      { src: `${base}acharya guru/5.jpg`, span: "" },
    ]
  },
  {
    id: "brisk-logo",
    number: "02",
    title: "BRISK Logo Design",
    tagline: "Minimalist logo with light color palette for an interior designer.",
    tags: ["Logo Design", "Minimalist", "Interior"],
    color: "#708090",
    thumbnail: `${base}BRISK Logo design for Interior designer/thumbnail.jpg`,
    images: [
      { src: `${base}BRISK Logo design for Interior designer/1.jpg`, span: "span-full" },
    ]
  },
  {
    id: "cake-shop-branding",
    number: "03",
    title: "The Yum Bakes",
    tagline: "Sweet and inviting brand identity for a cake shop.",
    tags: ["Branding", "Food", "Identity"],
    color: "#E8A0BF",
    thumbnail: `${base}Cake Shop Branding - The Yum Bakes/thumbnail.jpg`,
    images: [
      { src: `${base}Cake Shop Branding - The Yum Bakes/1.jpg`, span: "span-full" },
    ]
  },
  {
    id: "glozone-beauty",
    number: "04",
    title: "Glozone Beauty Lounge",
    tagline: "Elegant beauty lounge branding for premium wellness experiences.",
    tags: ["Beauty", "Branding", "Wellness"],
    color: "#DDA0DD",
    thumbnail: `${base}Glozone Beauty Lounge/thumbnail.jpg`,
    images: [
      { src: `${base}Glozone Beauty Lounge/1.webp`, span: "span-full" },
    ]
  },
  {
    id: "mirakle-coq10",
    number: "05",
    title: "Mirakle CoQ-10",
    tagline: "A clean, clinical approach to supplement packaging design.",
    tags: ["Supplement", "Visual Identity", "Packaging"],
    color: "#87CEEB",
    thumbnail: `${base}mirakle coq10/thumbnail.gif`,
    images: [
      { src: `${base}mirakle coq10/1.gif`, span: "span-full" },
      { src: `${base}mirakle coq10/2.webp`, span: "" },
      { src: `${base}mirakle coq10/3.webp`, span: "" },
      { src: `${base}mirakle coq10/4.webp`, span: "" },
      { src: `${base}mirakle coq10/5.webp`, span: "" },
      { src: `${base}mirakle coq10/6.webp`, span: "" },
      { src: `${base}mirakle coq10/7.webp`, span: "span-full" },
      { src: `${base}mirakle coq10/8.webp`, span: "" },
      { src: `${base}mirakle coq10/9.webp`, span: "" },
    ]
  },
  {
    id: "mirakle-mito",
    number: "06",
    title: "Mirakle Mr. MITO",
    tagline: "Vibrant and playful packaging for an energy drink brand.",
    tags: ["Packaging", "Energy Drink", "Illustration"],
    color: "#FF6B6B",
    thumbnail: `${base}mito/thumbnail.gif`,
    images: [
      { src: `${base}mito/1.gif`, span: "span-full" },
      { src: `${base}mito/2.gif`, span: "" },
      { src: `${base}mito/3.gif`, span: "" },
      { src: `${base}mito/4.gif`, span: "span-full" },
      { src: `${base}mito/5.gif`, span: "span-full" },
      { src: `${base}mito/6.jpg`, span: "span-full" },
    ]
  },
  {
    id: "nidra-nutrition",
    number: "07",
    title: "Nidra Nutrition",
    tagline: "Premium product packaging for a wellness brand.",
    tags: ["Nutrition", "Packaging", "Mockup"],
    color: "#9DC183",
    thumbnail: `${base}nidra/thumbnail.jpg`,
    images: [
      { src: `${base}nidra/1.jpg`, span: "span-full" },
      { src: `${base}nidra/2.jpg`, span: "" },
      { src: `${base}nidra/3.jpg`, span: "" },
      { src: `${base}nidra/4.jpg`, span: "span-full" },
      { src: `${base}nidra/5.jpg`, span: "" },
      { src: `${base}nidra/6.jpg`, span: "" },
    ]
  },
  {
    id: "niras-makeover",
    number: "08",
    title: "NIRA'S Makeover",
    tagline: "Glamorous make-up artist branding.",
    tags: ["Beauty", "Branding", "Makeup"],
    color: "#FFB6C1",
    thumbnail: `${base}NIRA'S Makeover/thumbnail.jpg`,
    images: [
      { src: `${base}NIRA'S Makeover/2.jpg`, span: "" },
      { src: `${base}NIRA'S Makeover/3.jpg`, span: "" },
    ]
  },
  {
    id: "random-illustrations",
    number: "09",
    title: "Random Illustrations",
    tagline: "A collection of creative illustrations.",
    tags: ["Illustration", "Creative", "Art"],
    color: "#FFD700",
    thumbnail: `${base}Random Illustrations/thumbnail.gif`,
    images: [
      { src: `${base}Random Illustrations/0.gif`, span: "" },
      { src: `${base}Random Illustrations/1.gif`, span: "" },
      { src: `${base}Random Illustrations/2.gif`, span: "" },
      { src: `${base}Random Illustrations/3.gif`, span: "" },
      { src: `${base}Random Illustrations/4.gif`, span: "" },
      { src: `${base}Random Illustrations/5.gif`, span: "" },
      { src: `${base}Random Illustrations/6.gif`, span: "" },
      { src: `${base}Random Illustrations/7.gif`, span: "" },
    ]
  },
  {
    id: "sha-outlet",
    number: "10",
    title: "Sha OUTLET Branding",
    tagline: "Bold costume designer fashion brand identity.",
    tags: ["Fashion", "Branding", "Streetwear"],
    color: "#2F4F4F",
    thumbnail: `${base}Sha OUTLET branding design/thumbnail.jpg`,
    images: [
      { src: `${base}Sha OUTLET branding design/1.webp`, span: "span-full" },
    ]
  },
  {
    id: "sivakannan-business",
    number: "11",
    title: "Sivakannan Business Card",
    tagline: "Sophisticated business card design.",
    tags: ["Business Card", "Print", "Identity"],
    color: "#556B2F",
    thumbnail: `${base}Sivakannan-business card/thumbnail.jpg`,
    images: [
      { src: `${base}Sivakannan-business card/1.webp`, span: "span-full" },
    ]
  },
  {
    id: "social-media-campaigns",
    number: "12",
    title: "Social Media Campaigns",
    tagline: "Multi-product social media campaign series.",
    tags: ["Social Media", "Campaign", "Marketing"],
    color: "#6B8E23",
    thumbnail: `${base}Social Media Campaigns-Multiple Products/thumbnail.jpg`,
    images: [
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_1.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_2.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_3.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_4.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_5.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_6.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_7.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_8.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_9.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_10.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_11.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_12.jpeg`, span: "" },
      { src: `${base}Social Media Campaigns-Multiple Products/behance_img_13.jpeg`, span: "span-full" },
    ]
  },
  {
    id: "cyclezone-social",
    number: "13",
    title: "Social Media - CycleZone",
    tagline: "Extensive social media creative series for a cycling brand.",
    tags: ["Social Media", "Cycling", "Creative"],
    color: "#FF4500",
    thumbnail: `${base}Social media creatives - CycleZone/thumbnail.jpg`,
    images: [
      { src: `${base}Social media creatives - CycleZone/behance_img_7.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_10.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_11.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_16.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_20.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_22.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_25.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_27.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_32.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_40.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_41.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_45.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_49.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_50.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_53.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_56.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_63.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_64.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_65.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_66.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_67.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_68.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_69.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_70.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_71.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_72.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_74.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_75.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_78.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_80.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_81.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_82.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_83.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_84.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_85.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_87.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_88.jpg`, span: "" },
      { src: `${base}Social media creatives - CycleZone/behance_img_89.jpg`, span: "" },
    ]
  },
  {
    id: "sprout-brochure",
    number: "14",
    title: "Sprout Brochure",
    tagline: "Nature-inspired brochure design with organic layouts.",
    tags: ["Brochure", "Print", "Nature"],
    color: "#8FBC8F",
    thumbnail: `${base}Sprout Brochure/thumbnail.webp`,
    images: [
      { src: `${base}Sprout Brochure/1.webp`, span: "" },
      { src: `${base}Sprout Brochure/2.webp`, span: "" },
      { src: `${base}Sprout Brochure/3.webp`, span: "" },
      { src: `${base}Sprout Brochure/4.webp`, span: "" },
    ]
  },
  {
    id: "hara-aesthetic",
    number: "15",
    title: "THE HARA AESTHETIC",
    tagline: "Premium makeup artist branding.",
    tags: ["Makeup", "Branding", "Beauty"],
    color: "#DEB887",
    thumbnail: `${base}THE HARA AESTHETIC Makeup artist/thumbnail.jpg`,
    images: [
      { src: `${base}THE HARA AESTHETIC Makeup artist/2.jpg`, span: "" },
      { src: `${base}THE HARA AESTHETIC Makeup artist/3.jpg`, span: "" },
      { src: `${base}THE HARA AESTHETIC Makeup artist/4.jpg`, span: "" },
      { src: `${base}THE HARA AESTHETIC Makeup artist/5.jpg`, span: "" },
      { src: `${base}THE HARA AESTHETIC Makeup artist/6.jpg`, span: "" },
    ]
  }
]